/**
 * Configuración centralizada de campos de Airtable
 * 
 * ⚠️ IMPORTANTE: Este archivo obtiene TODOS los nombres de campos desde variables de entorno.
 * NO hay fallbacks hardcodeados para garantizar que siempre se usen las configuraciones externas.
 * 
 * Si una variable de entorno no está configurada, el sistema fallará al acceder al campo
 * para evitar usar nombres hardcodeados accidentalmente.
 * 
 * Los campos usan evaluación lazy (getters) para que solo se validen cuando realmente
 * se acceden, evitando que un env var faltante crashee rutas que no lo usan.
 */

// Función helper para obtener campo requerido de variable de entorno
function getRequiredField(envVarName: string): string {
  const value = process.env[envVarName];
  if (!value) {
    throw new Error(`❌ Variable de entorno requerida no configurada: ${envVarName}`);
  }
  return value;
}

/**
 * Crea un objeto de campos con evaluación lazy.
 * Los valores se resuelven solo cuando se acceden, no al importar el módulo.
 * Esto permite que rutas que no usan ciertos campos no fallen si esos env vars no están configurados.
 */
function createLazyFields<T extends Record<string, string>>(
  envMapping: T
): Readonly<{ [K in keyof T]: string }> {
  const obj = {} as Record<string, string>;
  for (const [key, envName] of Object.entries(envMapping)) {
    Object.defineProperty(obj, key, {
      get() {
        return getRequiredField(envName);
      },
      enumerable: true,
      configurable: false,
    });
  }
  return obj as Readonly<{ [K in keyof T]: string }>;
}

/**
 * Campos de la tabla "Caja Menor"
 * Tabla principal que almacena los anticipos de caja menor mensuales
 */
export const CAJA_MENOR_FIELDS = createLazyFields({
  FECHA_ANTICIPO: 'AIRTABLE_FIELD_FECHA_ANTICIPO',
  BENEFICIARIO: 'AIRTABLE_FIELD_BENEFICIARIO',
  NIT_CC: 'AIRTABLE_FIELD_NIT_CC',
  CONCEPTO: 'AIRTABLE_FIELD_CONCEPTO_CAJA_MENOR',
  VALOR: 'AIRTABLE_FIELD_VALOR_CAJA_MENOR',
  REALIZA_REGISTRO: 'AIRTABLE_FIELD_REALIZA_REGISTRO',
  FECHA_CONSOLIDACION: 'AIRTABLE_FIELD_FECHA_CONSOLIDACION',
  DOCUMENTO_CONSOLIDACION: 'AIRTABLE_FIELD_DOCUMENTO_CONSOLIDACION',
  ESTADO_CAJA_MENOR: 'AIRTABLE_FIELD_ESTADO_CAJA_MENOR',
  URL_S3: 'AIRTABLE_FIELD_URL_S3',
  ITEMS_CAJA_MENOR: 'AIRTABLE_FIELD_ITEMS_CAJA_MENOR',
});

/**
 * Campos de la tabla "Items Caja Menor"
 * Tabla de detalle que almacena los gastos individuales de cada caja menor
 */
export const ITEMS_CAJA_MENOR_FIELDS = createLazyFields({
  ITEM: 'AIRTABLE_FIELD_ITEM',
  FECHA: 'AIRTABLE_FIELD_FECHA',
  BENEFICIARIO: 'AIRTABLE_FIELD_BENEFICIARIO_ITEMS',
  NIT_CC: 'AIRTABLE_FIELD_NIT_CC_ITEMS',
  CONCEPTO: 'AIRTABLE_FIELD_CONCEPTO_ITEMS',
  CENTRO_COSTO: 'AIRTABLE_FIELD_CENTRO_COSTO',
  VALOR: 'AIRTABLE_FIELD_VALOR_ITEMS',
  REALIZA_REGISTRO: 'AIRTABLE_FIELD_REALIZA_REGISTRO_ITEMS',
  COMPROBANTE: 'AIRTABLE_FIELD_COMPROBANTE',
  URL_S3: 'AIRTABLE_FIELD_URL_S3_ITEMS',
  CAJA_MENOR: 'AIRTABLE_FIELD_CAJA_MENOR',
});

/**
 * Tipo de datos para campos de Caja Menor
 */
export type CajaMenorFieldsType = typeof CAJA_MENOR_FIELDS;

/**
 * Tipo de datos para campos de Items Caja Menor
 */
export type ItemsCajaMenorFieldsType = typeof ITEMS_CAJA_MENOR_FIELDS;

/**
 * Campos de la tabla "Órdenes de Compra"
 */
export const OC_FIELDS = createLazyFields({
  ESTADO: 'AIRTABLE_FIELD_OC_ESTADO',
  PROVEEDOR: 'AIRTABLE_FIELD_OC_PROVEEDOR',
  FECHA_EMISION: 'AIRTABLE_FIELD_OC_FECHA_EMISION',
  PRIORIDAD: 'AIRTABLE_FIELD_OC_PRIORIDAD',
  ITEMS_OC_LINK: 'AIRTABLE_FIELD_OC_ITEMS_OC_LINK',
  ID_ORDEN_COMPRA: 'AIRTABLE_FIELD_OC_ID_ORDEN_COMPRA',
  NOMBRE_FROM_PROVEEDOR: 'AIRTABLE_FIELD_OC_NOMBRE_FROM_PROVEEDOR',
  NOMBRE_SOLICITANTE: 'AIRTABLE_FIELD_OC_NOMBRE_SOLICITANTE',
  CARGO_SOLICITANTE: 'AIRTABLE_FIELD_OC_CARGO_SOLICITANTE',
  AREA_CORRESPONDIENTE: 'AIRTABLE_FIELD_OC_AREA_CORRESPONDIENTE',
  AUTORIZADO_POR: 'AIRTABLE_FIELD_OC_AUTORIZADO_POR',
  DESCRIPCION: 'AIRTABLE_FIELD_OC_DESCRIPCION',
  SUBTOTAL: 'AIRTABLE_FIELD_OC_SUBTOTAL',
  IVA: 'AIRTABLE_FIELD_OC_IVA',
  RETENCION: 'AIRTABLE_FIELD_OC_RETENCION',
  TOTAL_NETO: 'AIRTABLE_FIELD_OC_TOTAL_NETO',
  DOCUMENTO_OC: 'AIRTABLE_FIELD_OC_DOCUMENTO_OC',
  COTIZACION_DOC_URL: 'AIRTABLE_FIELD_OC_COTIZACION_DOC_URL',
  COMENTARIOS: 'AIRTABLE_FIELD_OC_COMENTARIOS',
  FECHA_APROBACION: 'AIRTABLE_FIELD_OC_FECHA_APROBACION',
  COMPRA_RELACIONADA: 'AIRTABLE_FIELD_OC_COMPRA_RELACIONADA',
  COTIZACION_RELACIONADA: 'AIRTABLE_FIELD_OC_COTIZACION_RELACIONADA',
});

/**
 * Campos de la tabla "Items OC"
 */
export const ITEMS_OC_FIELDS = createLazyFields({
  ID_ITEM_OC: 'AIRTABLE_FIELD_IOC_ID_ITEM_OC',
  ORDEN_COMPRA_RELACIONADA: 'AIRTABLE_FIELD_IOC_ORDEN_COMPRA_RELACIONADA',
  DESCRIPCION: 'AIRTABLE_FIELD_IOC_DESCRIPCION',
  CENTRO_COSTOS: 'AIRTABLE_FIELD_IOC_CENTRO_COSTOS',
  CANTIDAD: 'AIRTABLE_FIELD_IOC_CANTIDAD',
  UNIDAD_MEDIDA: 'AIRTABLE_FIELD_IOC_UNIDAD_MEDIDA',
  VALOR_UNITARIO: 'AIRTABLE_FIELD_IOC_VALOR_UNITARIO',
  VALOR_TOTAL: 'AIRTABLE_FIELD_IOC_VALOR_TOTAL',
  COMENTARIOS: 'AIRTABLE_FIELD_IOC_COMENTARIOS',
  ITEM_COMPRA_RELACIONADO: 'AIRTABLE_FIELD_IOC_ITEM_COMPRA_RELACIONADO',
  ITEM_COTIZADO_RELACIONADO: 'AIRTABLE_FIELD_IOC_ITEM_COTIZADO_RELACIONADO',
});

/**
 * Campos de la tabla "Proveedores"
 */
export const PROVEEDORES_FIELDS = createLazyFields({
  NOMBRE: 'AIRTABLE_FIELD_PROV_NOMBRE',
  NIT: 'AIRTABLE_FIELD_PROV_NIT',
  CIUDAD: 'AIRTABLE_FIELD_PROV_CIUDAD',
});

/**
 * Campos de la tabla "Proyecciones"
 */
export const PROYECCIONES_FIELDS = createLazyFields({
  ANO_FORMULADO: 'AIRTABLE_FIELD_PROY_ANO_FORMULADO',
  SEMANA_FORMULADA: 'AIRTABLE_FIELD_PROY_SEMANA_FORMULADA',
  VR_PRESUPUESTO: 'AIRTABLE_FIELD_PROY_VR_PRESUPUESTO',
  MES: 'AIRTABLE_FIELD_PROY_MES',
  CONCEPTO: 'AIRTABLE_FIELD_PROY_CONCEPTO',
  CLASIFICACION: 'AIRTABLE_FIELD_PROY_CLASIFICACION',
  TIPO_MOVIMIENTO: 'AIRTABLE_FIELD_PROY_TIPO_MOVIMIENTO',
  TIPO_PROYECCION: 'AIRTABLE_FIELD_PROY_TIPO_PROYECCION',
  GRUPO: 'AIRTABLE_FIELD_PROY_GRUPO',
  CLASE: 'AIRTABLE_FIELD_PROY_CLASE',
});

/**
 * Campos de la tabla "Remisiones Laboratorio"
 */
export const REMISIONES_FIELDS = createLazyFields({
  NOMBRE_CLIENTES: 'AIRTABLE_FIELD_REM_NOMBRE_CLIENTES',
  TOTAL_LITROS: 'AIRTABLE_FIELD_REM_TOTAL_LITROS',
  VALOR_TOTAL_LITROS: 'AIRTABLE_FIELD_REM_VALOR_TOTAL_LITROS',
  NUMERO_REMISION: 'AIRTABLE_FIELD_REM_NUMERO_REMISION',
  NIT_CLIENTES: 'AIRTABLE_FIELD_REM_NIT_CLIENTES',
  FECHA_CREACION: 'AIRTABLE_FIELD_REM_FECHA_CREACION',
});

/**
 * Campos de la tabla "Compras y Adquisiciones"
 */
export const COMPRAS_FIELDS = createLazyFields({
  AREA_CORRESPONDIENTE: 'AIRTABLE_FIELD_COMPRAS_AREA_CORRESPONDIENTE',
  NOMBRE_SOLICITANTE: 'AIRTABLE_FIELD_COMPRAS_NOMBRE_SOLICITANTE',
  CARGO_SOLICITANTE: 'AIRTABLE_FIELD_COMPRAS_CARGO_SOLICITANTE',
  HAS_PROVIDER: 'AIRTABLE_FIELD_COMPRAS_HAS_PROVIDER',
  VALOR_UVT: 'AIRTABLE_FIELD_COMPRAS_VALOR_UVT',
  ESTADO_SOLICITUD: 'AIRTABLE_FIELD_COMPRAS_ESTADO_SOLICITUD',
  PRIORIDAD_SOLICITUD: 'AIRTABLE_FIELD_COMPRAS_PRIORIDAD_SOLICITUD',
  ITEMS_LINK: 'AIRTABLE_FIELD_COMPRAS_ITEMS_LINK',
  DESCRIPCION_TRANSCRIPCION: 'AIRTABLE_FIELD_COMPRAS_DESCRIPCION_TRANSCRIPCION',
  RAZON_SOCIAL_PROVEEDOR: 'AIRTABLE_FIELD_COMPRAS_RAZON_SOCIAL_PROVEEDOR',
  COTIZACION_DOC: 'AIRTABLE_FIELD_COMPRAS_COTIZACION_DOC',
  FECHA_SOLICITUD: 'AIRTABLE_FIELD_COMPRAS_FECHA_SOLICITUD',
  DESCRIPCION_IA: 'AIRTABLE_FIELD_COMPRAS_DESCRIPCION_IA',
  DOCUMENTO_SOLICITUD: 'AIRTABLE_FIELD_COMPRAS_DOCUMENTO_SOLICITUD',
  VALOR_TOTAL: 'AIRTABLE_FIELD_COMPRAS_VALOR_TOTAL',
  TOTAL_NETO: 'AIRTABLE_FIELD_COMPRAS_TOTAL_NETO',
  IVA: 'AIRTABLE_FIELD_COMPRAS_IVA',
  RETENCION: 'AIRTABLE_FIELD_COMPRAS_RETENCION',
  COMPRA_SERVICIO: 'AIRTABLE_FIELD_COMPRAS_COMPRA_SERVICIO',
  PROVEEDOR: 'AIRTABLE_FIELD_COMPRAS_PROVEEDOR',
  NOMBRE_FROM_PROVEEDOR: 'AIRTABLE_FIELD_COMPRAS_NOMBRE_FROM_PROVEEDOR',
  NIT_FROM_PROVEEDOR: 'AIRTABLE_FIELD_COMPRAS_NIT_FROM_PROVEEDOR',
  COTIZACIONES: 'AIRTABLE_FIELD_COMPRAS_COTIZACIONES',
  NOMBRES_ADMIN: 'AIRTABLE_FIELD_COMPRAS_NOMBRES_ADMIN',
  CLASIFICACION_BANCARIA: 'AIRTABLE_FIELD_COMPRAS_CLASIFICACION_BANCARIA',
  VALOR_BANCARIO: 'AIRTABLE_FIELD_COMPRAS_VALOR_BANCARIO',
  NUMERO_SEMANA_BANCARIO: 'AIRTABLE_FIELD_COMPRAS_NUMERO_SEMANA_BANCARIO',
  PROYECCION_BANCARIA: 'AIRTABLE_FIELD_COMPRAS_PROYECCION_BANCARIA',
  BASE_MINIMA_UVT: 'AIRTABLE_FIELD_COMPRAS_BASE_MINIMA_UVT',
  BASE_MINIMA_PESOS: 'AIRTABLE_FIELD_COMPRAS_BASE_MINIMA_PESOS',
  CIUDAD_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_CIUDAD_FROM_PROV',
  DEPARTAMENTO_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_DEPARTAMENTO_FROM_PROV',
  PERSONA_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_PERSONA_FROM_PROV',
  DECLARANTE_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_DECLARANTE_FROM_PROV',
  AUTORETENEDOR_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_AUTORETENEDOR_FROM_PROV',
  RESPONSABLE_IVA_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_RESPONSABLE_IVA_FROM_PROV',
  RESPONSABLE_ICA_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_RESPONSABLE_ICA_FROM_PROV',
  TARIFA_ACTIVIDAD_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_TARIFA_ACTIVIDAD_FROM_PROV',
  FACTURADOR_ELEC_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_FACTURADOR_ELEC_FROM_PROV',
  RUT_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_RUT_FROM_PROV',
  CONTRIBUYENTE_FROM_PROV: 'AIRTABLE_FIELD_COMPRAS_CONTRIBUYENTE_FROM_PROV',
});

/**
 * Campos de la tabla "Items" (Items de Solicitudes de Compra)
 */
export const ITEMS_COMPRAS_FIELDS = createLazyFields({
  OBJETO: 'AIRTABLE_FIELD_ICOMPRAS_OBJETO',
  CENTRO_COSTOS: 'AIRTABLE_FIELD_ICOMPRAS_CENTRO_COSTOS',
  CANTIDAD: 'AIRTABLE_FIELD_ICOMPRAS_CANTIDAD',
  VALOR_ITEM: 'AIRTABLE_FIELD_ICOMPRAS_VALOR_ITEM',
  VALOR_UVT: 'AIRTABLE_FIELD_ICOMPRAS_VALOR_UVT',
  ESTADO_ITEM: 'AIRTABLE_FIELD_ICOMPRAS_ESTADO_ITEM',
  COMPRA_SERVICIO: 'AIRTABLE_FIELD_ICOMPRAS_COMPRA_SERVICIO',
  PRIORIDAD: 'AIRTABLE_FIELD_ICOMPRAS_PRIORIDAD',
  FECHA_REQUERIDA: 'AIRTABLE_FIELD_ICOMPRAS_FECHA_REQUERIDA',
  FORMA_PAGO: 'AIRTABLE_FIELD_ICOMPRAS_FORMA_PAGO',
  RECIBO_REMISION: 'AIRTABLE_FIELD_ICOMPRAS_RECIBO_REMISION',
  COMPRA_Y_ADQUISICION: 'AIRTABLE_FIELD_ICOMPRAS_COMPRA_Y_ADQUISICION',
  APROBACION: 'AIRTABLE_FIELD_ICOMPRAS_APROBACION',
  ESTADO_GESTION: 'AIRTABLE_FIELD_ICOMPRAS_ESTADO_GESTION',
  TRANSPORTE: 'AIRTABLE_FIELD_ICOMPRAS_TRANSPORTE',
  NOMBRE_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_NOMBRE_FROM_PROV',
  NIT_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_NIT_FROM_PROV',
  CIUDAD_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_CIUDAD_FROM_PROV',
  DEPTO_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_DEPTO_FROM_PROV',
  PERSONA_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_PERSONA_FROM_PROV',
  DECLARANTE_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_DECLARANTE_FROM_PROV',
  AUTORETENEDOR_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_AUTORETENEDOR_FROM_PROV',
  RESP_IVA_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_RESP_IVA_FROM_PROV',
  RESP_ICA_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_RESP_ICA_FROM_PROV',
  TARIFA_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_TARIFA_FROM_PROV',
  FACTURADOR_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_FACTURADOR_FROM_PROV',
  RUT_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_RUT_FROM_PROV',
  CONTRIBUYENTE_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_CONTRIBUYENTE_FROM_PROV',
  CORREO_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_CORREO_FROM_PROV',
  CELULAR_FROM_PROV: 'AIRTABLE_FIELD_ICOMPRAS_CELULAR_FROM_PROV',
});

/**
 * Campos de la tabla "Movimientos Bancarios BBVA"
 */
export const BBVA_FIELDS = createLazyFields({
  CREADA: 'AIRTABLE_FIELD_BBVA_CREADA',
  FECHA: 'AIRTABLE_FIELD_BBVA_FECHA',
  SALDO_BANCARIO_ACTUAL: 'AIRTABLE_FIELD_BBVA_SALDO_BANCARIO_ACTUAL',
  DESCRIPCION: 'AIRTABLE_FIELD_BBVA_DESCRIPCION',
  VALOR: 'AIRTABLE_FIELD_BBVA_VALOR',
});

/**
 * Campos de la tabla "Insumo" (Sirius Insumos Core)
 */
export const INSUMO_FIELDS = createLazyFields({
  ID: 'AIRTABLE_FIELD_INS_ID',
  NOMBRE: 'AIRTABLE_FIELD_INS_NOMBRE',
  CODIGO_SIRIUS: 'AIRTABLE_FIELD_INS_CODIGO_SIRIUS',
  UNIDAD_MEDIDA: 'AIRTABLE_FIELD_INS_UNIDAD_MEDIDA',
  UNIDAD_BASE: 'AIRTABLE_FIELD_INS_UNIDAD_BASE',
  STOCK_MINIMO: 'AIRTABLE_FIELD_INS_STOCK_MINIMO',
  ESTADO: 'AIRTABLE_FIELD_INS_ESTADO',
  FICHA_TECNICA: 'AIRTABLE_FIELD_INS_FICHA_TECNICA',
  REFERENCIA_COMERCIAL: 'AIRTABLE_FIELD_INS_REFERENCIA_COMERCIAL',
  CATEGORIA: 'AIRTABLE_FIELD_INS_CATEGORIA',
  IMAGEN_REFERENCIA: 'AIRTABLE_FIELD_INS_IMAGEN_REFERENCIA',
});

/**
 * Campos de la tabla "Areas" (Sirius Insumos Core)
 */
export const AREA_FIELDS = createLazyFields({
  NOMBRE: 'AIRTABLE_FIELD_AREA_NOMBRE',
  ID_CORE: 'AIRTABLE_FIELD_AREA_ID_CORE',
  RESPONSABLE: 'AIRTABLE_FIELD_AREA_RESPONSABLE',
  ACTIVA: 'AIRTABLE_FIELD_AREA_ACTIVA',
});

/**
 * Campos de la tabla "Balances de Masa"
 */
export const BALANCES_MASA_FIELDS = createLazyFields({
  FECHA: 'AIRTABLE_FIELD_BM_FECHA',
});

/**
 * Campos de la tabla "Conversaciones"
 */
export const CONVERSACIONES_FIELDS = createLazyFields({
  SOLICITUD_COMPRA: 'AIRTABLE_FIELD_CONV_SOLICITUD_COMPRA',
  FECHA_HORA_MENSAJE: 'AIRTABLE_FIELD_CONV_FECHA_HORA_MENSAJE',
  ID_CONVERSACION: 'AIRTABLE_FIELD_CONV_ID_CONVERSACION',
  REMITENTE: 'AIRTABLE_FIELD_CONV_REMITENTE',
  NOMBRE_REMITENTE: 'AIRTABLE_FIELD_CONV_NOMBRE_REMITENTE',
  MENSAJE: 'AIRTABLE_FIELD_CONV_MENSAJE',
  REALIZA_REGISTRO: 'AIRTABLE_FIELD_CONV_REALIZA_REGISTRO',
  FECHA_HORA_VISTO: 'AIRTABLE_FIELD_CONV_FECHA_HORA_VISTO',
});

/**
 * Campos de la tabla "Cotizaciones"
 */
export const COTIZACION_FIELDS = createLazyFields({
  ID_COTIZACION: 'AIRTABLE_FIELD_COT_ID_COTIZACION',
  FECHA: 'AIRTABLE_FIELD_COT_FECHA',
  SOLICITANTE: 'AIRTABLE_FIELD_COT_SOLICITANTE',
  COMPRA_RELACIONADA: 'AIRTABLE_FIELD_COT_COMPRA_RELACIONADA',
  ESTADO: 'AIRTABLE_FIELD_COT_ESTADO',
  DOCUMENTO: 'AIRTABLE_FIELD_COT_DOCUMENTO',
  COMENTARIOS: 'AIRTABLE_FIELD_COT_COMENTARIOS',
  PROVEEDOR: 'AIRTABLE_FIELD_COT_PROVEEDOR',
  ITEMS_COTIZADOS: 'AIRTABLE_FIELD_COT_ITEMS_COTIZADOS',
});

/**
 * Campos de la tabla "Items Cotizados"
 */
export const ITEMS_COTIZADOS_FIELDS = createLazyFields({
  ID_ITEM_COTIZADO: 'AIRTABLE_FIELD_ICOT_ID_ITEM_COTIZADO',
  COTIZACION_RELACIONADA: 'AIRTABLE_FIELD_ICOT_COTIZACION_RELACIONADA',
  DESCRIPCION: 'AIRTABLE_FIELD_ICOT_DESCRIPCION',
  CANTIDAD: 'AIRTABLE_FIELD_ICOT_CANTIDAD',
  UNIDAD_MEDIDA: 'AIRTABLE_FIELD_ICOT_UNIDAD_MEDIDA',
  VALOR_UNITARIO: 'AIRTABLE_FIELD_ICOT_VALOR_UNITARIO',
  COMENTARIOS: 'AIRTABLE_FIELD_ICOT_COMENTARIOS',
  ITEM_COMPRA_RELACIONADO: 'AIRTABLE_FIELD_ICOT_ITEM_COMPRA_RELACIONADO',
});

/**
 * Campos de la tabla "Facturación Ingresos"
 */
export const FACTURACION_INGRESOS_FIELDS = createLazyFields({
  CENTRO_RESULTADOS: 'AIRTABLE_FIELD_FING_CENTRO_RESULTADOS',
  ANO_FORMULADO: 'AIRTABLE_FIELD_FING_ANO_FORMULADO',
  MES_FORMULADO: 'AIRTABLE_FIELD_FING_MES_FORMULADO',
  CREADA: 'AIRTABLE_FIELD_FING_CREADA',
  VALOR: 'AIRTABLE_FIELD_FING_VALOR',
  OBSERVACIONES: 'AIRTABLE_FIELD_FING_OBSERVACIONES',
  CUFE: 'AIRTABLE_FIELD_FING_CUFE',
});

/**
 * Campos de la tabla "Centralización General"
 */
export const CENTRALIZACION_FIELDS = createLazyFields({
  ANO_FORMULADO: 'AIRTABLE_FIELD_CENT_ANO_FORMULADO',
  NUMERO_MES: 'AIRTABLE_FIELD_CENT_NUMERO_MES',
  SEMANA_FORMULADA: 'AIRTABLE_FIELD_CENT_SEMANA_FORMULADA',
  FECHA_CREACION: 'AIRTABLE_FIELD_CENT_FECHA_CREACION',
  MES: 'AIRTABLE_FIELD_CENT_MES',
  UNB_PURPUREOCILLIUM: 'AIRTABLE_FIELD_CENT_UNB_PURPUREOCILLIUM',
  UNB_METARHIZIUM: 'AIRTABLE_FIELD_CENT_UNB_METARHIZIUM',
  UNB_BACILLUS: 'AIRTABLE_FIELD_CENT_UNB_BACILLUS',
  UNB_SIRIUSBACTER: 'AIRTABLE_FIELD_CENT_UNB_SIRIUSBACTER',
  UNB_BEAUVERIA: 'AIRTABLE_FIELD_CENT_UNB_BEAUVERIA',
  UNB_TRICHODERMA: 'AIRTABLE_FIELD_CENT_UNB_TRICHODERMA',
  TOTAL_UNB: 'AIRTABLE_FIELD_CENT_TOTAL_UNB',
  UNP_BIOCHAR_PURO: 'AIRTABLE_FIELD_CENT_UNP_BIOCHAR_PURO',
  UNP_BIOCHAR_FILTRO: 'AIRTABLE_FIELD_CENT_UNP_BIOCHAR_FILTRO',
  UNP_BIOCHAR_INOCULADO: 'AIRTABLE_FIELD_CENT_UNP_BIOCHAR_INOCULADO',
  UNP_BIOCHAR_BLEND: 'AIRTABLE_FIELD_CENT_UNP_BIOCHAR_BLEND',
  TOTAL_UNP: 'AIRTABLE_FIELD_CENT_TOTAL_UNP',
  INGRESOS_TOTALES_UNB: 'AIRTABLE_FIELD_CENT_INGRESOS_TOTALES_UNB',
  INGRESOS_TOTALES_UNP: 'AIRTABLE_FIELD_CENT_INGRESOS_TOTALES_UNP',
  INGRESOS_OPERACIONALES: 'AIRTABLE_FIELD_CENT_INGRESOS_OPERACIONALES',
  INGRESOS_NO_OPERACIONALES: 'AIRTABLE_FIELD_CENT_INGRESOS_NO_OPERACIONALES',
  TOTAL_INGRESOS: 'AIRTABLE_FIELD_CENT_TOTAL_INGRESOS',
  INGRESOS_ESTIMADOS: 'AIRTABLE_FIELD_CENT_INGRESOS_ESTIMADOS',
  MOVIMIENTO_COSTOS: 'AIRTABLE_FIELD_CENT_MOVIMIENTO_COSTOS',
  MOVIMIENTO_GASTOS: 'AIRTABLE_FIELD_CENT_MOVIMIENTO_GASTOS',
  MOVIMIENTO_INVERSION: 'AIRTABLE_FIELD_CENT_MOVIMIENTO_INVERSION',
  TOTAL_EGRESOS: 'AIRTABLE_FIELD_CENT_TOTAL_EGRESOS',
  EGRESOS_ESTIMADOS: 'AIRTABLE_FIELD_CENT_EGRESOS_ESTIMADOS',
  TOTAL_COSTOS_GASTOS_PIROLISIS: 'AIRTABLE_FIELD_CENT_TOTAL_COSTOS_GASTOS_PIROLISIS',
  SALDO_INICIAL_BANCOS: 'AIRTABLE_FIELD_CENT_SALDO_INICIAL_BANCOS',
  SALDO_FINAL_BANCOS: 'AIRTABLE_FIELD_CENT_SALDO_FINAL_BANCOS',
  NETO_SEMANAL_BANCOS: 'AIRTABLE_FIELD_CENT_NETO_SEMANAL_BANCOS',
  SALDO_INICIO_PROYECTADO: 'AIRTABLE_FIELD_CENT_SALDO_INICIO_PROYECTADO',
  SALDO_FINAL_PROYECTADO: 'AIRTABLE_FIELD_CENT_SALDO_FINAL_PROYECTADO',
  NETO_SEMANAL_PROYECTADO: 'AIRTABLE_FIELD_CENT_NETO_SEMANAL_PROYECTADO',
  CANT_LITROS_DEBERIA: 'AIRTABLE_FIELD_CENT_CANT_LITROS_DEBERIA',
  CANT_KG_DEBERIA: 'AIRTABLE_FIELD_CENT_CANT_KG_DEBERIA',
});

/**
 * Campos de la tabla "Personal" (Nómina Core)
 */
export const NOMINA_PERSONAL_FIELDS = createLazyFields({
  ESTADO_ACTIVIDAD: 'AIRTABLE_FIELD_NOM_ESTADO_ACTIVIDAD',
  NOMBRE_COMPLETO: 'AIRTABLE_FIELD_NOM_NOMBRE_COMPLETO',
  CEDULA: 'AIRTABLE_FIELD_NOM_CEDULA',
  ROL: 'AIRTABLE_FIELD_NOM_ROL',
  AREAS: 'AIRTABLE_FIELD_NOM_AREAS',
});

/**
 * Campos de la tabla "Roles" (Nómina Core)
 */
export const NOMINA_ROLES_FIELDS = createLazyFields({
  NOMBRE_ROL: 'AIRTABLE_FIELD_NOM_NOMBRE_ROL',
});

/**
 * Campos de la tabla "Áreas" (Nómina Core)
 */
export const NOMINA_AREAS_FIELDS = createLazyFields({
  NOMBRE_AREA: 'AIRTABLE_FIELD_NOM_NOMBRE_AREA',
});

/**
 * Campos de la tabla "Facturación Egresos"
 */
export const FACTURACION_EGRESOS_FIELDS = createLazyFields({
  BANCO_Y_PROYECCION: 'AIRTABLE_FIELD_FEGR_BANCO_Y_PROYECCION',
  FECHA_EMISION: 'AIRTABLE_FIELD_FEGR_FECHA_EMISION',
  NUMERO_FACTURA: 'AIRTABLE_FIELD_FEGR_NUMERO_FACTURA',
  EMISOR: 'AIRTABLE_FIELD_FEGR_EMISOR',
  ITEMS_FACTURA: 'AIRTABLE_FIELD_FEGR_ITEMS_FACTURA',
  ID: 'AIRTABLE_FIELD_FEGR_ID',
  NIT_EMISOR: 'AIRTABLE_FIELD_FEGR_NIT_EMISOR',
  DIRECCION_EMISOR: 'AIRTABLE_FIELD_FEGR_DIRECCION_EMISOR',
  FORMA_PAGO: 'AIRTABLE_FIELD_FEGR_FORMA_PAGO',
  CONDICIONES_PAGO: 'AIRTABLE_FIELD_FEGR_CONDICIONES_PAGO',
  MONEDA: 'AIRTABLE_FIELD_FEGR_MONEDA',
  SUBTOTAL: 'AIRTABLE_FIELD_FEGR_SUBTOTAL',
  DESCUENTOS: 'AIRTABLE_FIELD_FEGR_DESCUENTOS',
  IVA: 'AIRTABLE_FIELD_FEGR_IVA',
  INC: 'AIRTABLE_FIELD_FEGR_INC',
  RETENCION: 'AIRTABLE_FIELD_FEGR_RETENCION',
  RETEIVA: 'AIRTABLE_FIELD_FEGR_RETEIVA',
  RETEICA: 'AIRTABLE_FIELD_FEGR_RETEICA',
  TOTAL_PAGAR: 'AIRTABLE_FIELD_FEGR_TOTAL_PAGAR',
  C_COSTOS: 'AIRTABLE_FIELD_FEGR_C_COSTOS',
  GRUPO: 'AIRTABLE_FIELD_FEGR_GRUPO',
  CLASE: 'AIRTABLE_FIELD_FEGR_CLASE',
  CUENTA: 'AIRTABLE_FIELD_FEGR_CUENTA',
  SUB_CUENTA: 'AIRTABLE_FIELD_FEGR_SUB_CUENTA',
  TIPO_RETENCION: 'AIRTABLE_FIELD_FEGR_TIPO_RETENCION',
  TIPO_OPERACION: 'AIRTABLE_FIELD_FEGR_TIPO_OPERACION',
  CUFE: 'AIRTABLE_FIELD_FEGR_CUFE',
  FECHA_VENCIMIENTO: 'AIRTABLE_FIELD_FEGR_FECHA_VENCIMIENTO',
  PRODUCTO_TERMINADO: 'AIRTABLE_FIELD_FEGR_PRODUCTO_TERMINADO',
  CLASIFICACION_COSTO: 'AIRTABLE_FIELD_FEGR_CLASIFICACION_COSTO',
  PARA_EFECTOS_CONTABLES: 'AIRTABLE_FIELD_FEGR_PARA_EFECTOS_CONTABLES',
});

/**
 * Campos de la tabla "Items Facturación Egresos"
 */
export const ITEM_FACTURACION_EGRESOS_FIELDS = createLazyFields({
  ITEM: 'AIRTABLE_FIELD_IFEGR_ITEM',
  UNIDAD: 'AIRTABLE_FIELD_IFEGR_UNIDAD',
  CANTIDAD: 'AIRTABLE_FIELD_IFEGR_CANTIDAD',
  VR_UNITARIO: 'AIRTABLE_FIELD_IFEGR_VR_UNITARIO',
  VR_TOTAL_FLOW: 'AIRTABLE_FIELD_IFEGR_VR_TOTAL_FLOW',
  UNIDAD_NEGOCIO: 'AIRTABLE_FIELD_IFEGR_UNIDAD_NEGOCIO',
  CENTRO_COSTO: 'AIRTABLE_FIELD_IFEGR_CENTRO_COSTO',
  COMENTARIOS: 'AIRTABLE_FIELD_IFEGR_COMENTARIOS',
  TIPO_RTFE: 'AIRTABLE_FIELD_IFEGR_TIPO_RTFE',
});

/**
 * Campos de la tabla "Pago de Facturas"
 */
export const PAGO_FACTURAS_FIELDS = createLazyFields({
  ESTADO_FACTURA: 'AIRTABLE_FIELD_PF_ESTADO_FACTURA',
  FECHA_CREACION: 'AIRTABLE_FIELD_PF_FECHA_CREACION',
  FACTURA_NO: 'AIRTABLE_FIELD_PF_FACTURA_NO',
  NOMBRE_COMPRADOR: 'AIRTABLE_FIELD_PF_NOMBRE_COMPRADOR',
  NIT_COMPRADOR: 'AIRTABLE_FIELD_PF_NIT_COMPRADOR',
  TOTAL_RECIBIR: 'AIRTABLE_FIELD_PF_TOTAL_RECIBIR',
  SALDO_ANTERIOR: 'AIRTABLE_FIELD_PF_SALDO_ANTERIOR',
  MONTO_RESTANTE: 'AIRTABLE_FIELD_PF_MONTO_RESTANTE',
  TOTAL_MOVIMIENTOS: 'AIRTABLE_FIELD_PF_TOTAL_MOVIMIENTOS',
  ULTIMA_MODIFICACION: 'AIRTABLE_FIELD_PF_ULTIMA_MODIFICACION',
  ID_FACTURA: 'AIRTABLE_FIELD_PF_ID_FACTURA',
  MOVIMIENTOS_BANCARIOS: 'AIRTABLE_FIELD_PF_MOVIMIENTOS_BANCARIOS',
});

/**
 * Campos de la tabla "Movimientos Bancarios" (general)
 */
export const MOVIMIENTOS_BANCARIOS_FIELDS = createLazyFields({
  FECHA: 'AIRTABLE_FIELD_MOV_FECHA',
  ANO_FORMULADO: 'AIRTABLE_FIELD_MOV_ANO_FORMULADO',
  NUMERO_MES_FORMULADO: 'AIRTABLE_FIELD_MOV_NUMERO_MES_FORMULADO',
});

/**
 * Campos de la tabla "Movimientos Bancarios Bancolombia"
 */
export const BANCOLOMBIA_FIELDS = createLazyFields({
  FECHA: 'AIRTABLE_FIELD_BCOL_FECHA',
  DESCRIPCION: 'AIRTABLE_FIELD_BCOL_DESCRIPCION',
  CLASIFICACION: 'AIRTABLE_FIELD_BCOL_CLASIFICACION',
  VALOR: 'AIRTABLE_FIELD_BCOL_VALOR',
  CENTRO_COSTOS: 'AIRTABLE_FIELD_BCOL_CENTRO_COSTOS',
  FIJO_VARIABLE: 'AIRTABLE_FIELD_BCOL_FIJO_VARIABLE',
  NATURALEZA_CONTABLE: 'AIRTABLE_FIELD_BCOL_NATURALEZA_CONTABLE',
  LEGALIZACION: 'AIRTABLE_FIELD_BCOL_LEGALIZACION',
  AFECTA: 'AIRTABLE_FIELD_BCOL_AFECTA',
});

/**
 * Campos de la tabla "Movimientos Insumos" (Sirius Insumos Core)
 */
export const MOVIMIENTO_INSUMO_FIELDS = createLazyFields({
  CODIGO: 'AIRTABLE_FIELD_MINS_CODIGO',
  ID: 'AIRTABLE_FIELD_MINS_ID',
  NOMBRE: 'AIRTABLE_FIELD_MINS_NOMBRE',
  CANTIDAD: 'AIRTABLE_FIELD_MINS_CANTIDAD',
  TIPO_MOVIMIENTO: 'AIRTABLE_FIELD_MINS_TIPO_MOVIMIENTO',
  SUBTIPO: 'AIRTABLE_FIELD_MINS_SUBTIPO',
  CANTIDAD_ORIGINAL: 'AIRTABLE_FIELD_MINS_CANTIDAD_ORIGINAL',
  UNIDAD_ORIGINAL: 'AIRTABLE_FIELD_MINS_UNIDAD_ORIGINAL',
  FACTOR_CONVERSION: 'AIRTABLE_FIELD_MINS_FACTOR_CONVERSION',
  CANTIDAD_BASE: 'AIRTABLE_FIELD_MINS_CANTIDAD_BASE',
  COSTO_UNITARIO: 'AIRTABLE_FIELD_MINS_COSTO_UNITARIO',
  COSTO_TOTAL: 'AIRTABLE_FIELD_MINS_COSTO_TOTAL',
  COSTO_UNITARIO_BASE: 'AIRTABLE_FIELD_MINS_COSTO_UNITARIO_BASE',
  DOCUMENTO_ORIGEN: 'AIRTABLE_FIELD_MINS_DOCUMENTO_ORIGEN',
  ID_SOLICITUD_COMPRA: 'AIRTABLE_FIELD_MINS_ID_SOLICITUD_COMPRA',
  LOTE: 'AIRTABLE_FIELD_MINS_LOTE',
  FECHA_VENCIMIENTO: 'AIRTABLE_FIELD_MINS_FECHA_VENCIMIENTO',
  NOTAS: 'AIRTABLE_FIELD_MINS_NOTAS',
  ESTADO: 'AIRTABLE_FIELD_MINS_ESTADO',
  ID_RESPONSABLE: 'AIRTABLE_FIELD_MINS_ID_RESPONSABLE',
  AREA_ORIGEN: 'AIRTABLE_FIELD_MINS_AREA_ORIGEN',
  AREA_DESTINO: 'AIRTABLE_FIELD_MINS_AREA_DESTINO',
  AREA_DESTINO_LINK: 'AIRTABLE_FIELD_MINS_AREA_DESTINO_LINK',
  AREA_ORIGEN_LINK: 'AIRTABLE_FIELD_MINS_AREA_ORIGEN_LINK',
  CREADA: 'AIRTABLE_FIELD_MINS_CREADA',
  ULTIMA_MODIFICACION: 'AIRTABLE_FIELD_MINS_ULTIMA_MODIFICACION',
  INSUMO_LINK: 'AIRTABLE_FIELD_MINS_INSUMO_LINK',
  STOCK_LINK: 'AIRTABLE_FIELD_MINS_STOCK_LINK',
});

/**
 * Campos de la tabla "Unidades" (Sirius Insumos Core)
 */
export const UNIDAD_FIELDS = createLazyFields({
  NOMBRE: 'AIRTABLE_FIELD_UNI_NOMBRE',
  SIMBOLO: 'AIRTABLE_FIELD_UNI_SIMBOLO',
  TIPO: 'AIRTABLE_FIELD_UNI_TIPO',
  FACTOR_A_BASE: 'AIRTABLE_FIELD_UNI_FACTOR_A_BASE',
  UNIDAD_BASE_DE_TIPO: 'AIRTABLE_FIELD_UNI_UNIDAD_BASE_DE_TIPO',
});

/**
 * Campos de la tabla "Categorías Insumo" (Sirius Insumos Core)
 */
export const CATEGORIA_INSUMO_FIELDS = createLazyFields({
  CODIGO: 'AIRTABLE_FIELD_CATINS_CODIGO',
  ID: 'AIRTABLE_FIELD_CATINS_ID',
  TIPO_INSUMO: 'AIRTABLE_FIELD_CATINS_TIPO_INSUMO',
  DESCRIPCION: 'AIRTABLE_FIELD_CATINS_DESCRIPCION',
  INSUMO_LINK: 'AIRTABLE_FIELD_CATINS_INSUMO_LINK',
});

/**
 * Campos de la tabla "Stock Insumos" (Sirius Insumos Core)
 */
export const STOCK_INSUMO_FIELDS = createLazyFields({
  ID_STOCK: 'AIRTABLE_FIELD_STKINS_ID_STOCK',
  ID: 'AIRTABLE_FIELD_STKINS_ID',
  STOCK_ACTUAL: 'AIRTABLE_FIELD_STKINS_STOCK_ACTUAL',
  ULTIMA_ACTUALIZACION: 'AIRTABLE_FIELD_STKINS_ULTIMA_ACTUALIZACION',
  CANTIDAD_INGRESA: 'AIRTABLE_FIELD_STKINS_CANTIDAD_INGRESA',
  CANTIDAD_SALE: 'AIRTABLE_FIELD_STKINS_CANTIDAD_SALE',
  INSUMO_LINK: 'AIRTABLE_FIELD_STKINS_INSUMO_LINK',
  MOVIMIENTO_LINK: 'AIRTABLE_FIELD_STKINS_MOVIMIENTO_LINK',
  AREA: 'AIRTABLE_FIELD_STKINS_AREA',
  COSTO_ACUMULADO: 'AIRTABLE_FIELD_STKINS_COSTO_ACUMULADO',
});
